apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-storage-deployment
  labels:
    app: data-storage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-storage
  template:
    metadata:
      labels:
        app: data-storage
    spec:
      containers:
      - name: data-storage-app
        image: data-storage
        envFrom:
        - configMapRef:
            name: data-storage-env
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
