apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-storage-deployment
  labels:
    app: data-storage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-storage
  template:
    metadata:
      labels:
        app: data-storage
    spec:
      containers:
      - name: data-storage-app
        image: europe-west2-docker.pkg.dev/helical-theater-274414/docker-repository/data-storage:main
        env:
          - name: PORT
            value: "8080"
          - name: SERVICE_URL
            value: "https://dont-know-yet/"
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
