resources:
- ../../base
- ./mapping.yaml
- ./host.yaml
namePrefix: dev-
images:
- name: data-storage
  newName: europe-west2-docker.pkg.dev/helical-theater-274414/docker-repository/data-storage
  newTag: sha-f60ef4d2
configMapGenerator:
- name: data-storage-env
  literals:
    - PORT=8080
    - SERVICE_URL=https://keep.gke.ruiramos.com/
    - REDIS_URL=dev-redis-service.default.svc.cluster.local
